//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyAmThucNhaTrang.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class DANHGIA
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DANHGIA()
        {
            this.PHANHOI = new HashSet<PHANHOI>();
        }
    
        public int MaDG { get; set; }
        public int SoSao { get; set; }
        public string NoiDung { get; set; }
        public System.DateTime NgayDanhGia { get; set; }
        public string TrangThai { get; set; }
        public int MaTK { get; set; }
        public int MaDD { get; set; }
    
        public virtual DIADIEM DIADIEM { get; set; }
        public virtual TAIKHOAN TAIKHOAN { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PHANHOI> PHANHOI { get; set; }
    }
}
