//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyAmThucNhaTrang.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class DIADIEM
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DIADIEM()
        {
            this.DANHGIA = new HashSet<DANHGIA>();
            this.HINHANH = new HashSet<HINHANH>();
            this.KHUYENMAI = new HashSet<KHUYENMAI>();
            this.YEUTHICH = new HashSet<YEUTHICH>();
            this.DIADIEM1 = new HashSet<DIADIEM>();
        }
    
        public int MaDD { get; set; }
        public string TenDD { get; set; }
        public string DiaChiChiTiet { get; set; }
        public double ViDo { get; set; }
        public double KinhDo { get; set; }
        public string SDT { get; set; }
        public Nullable<System.TimeSpan> GioMoCua { get; set; }
        public Nullable<System.TimeSpan> GioDongCua { get; set; }
        public string MoTa { get; set; }
        public string TrangThai { get; set; }
        public double DiemDanhGiaTB { get; set; }
        public int SoLuotDanhGia { get; set; }
        public System.DateTime NgayDangKy { get; set; }
        public int MaTK { get; set; }
        public int MaDM { get; set; }
        public int MaKV { get; set; }
        public string LyDoTuChoi { get; set; }
        public Nullable<int> MaDD_Goc { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DANHGIA> DANHGIA { get; set; }
        public virtual DANHMUC DANHMUC { get; set; }
        public virtual KHUVUC KHUVUC { get; set; }
        public virtual TAIKHOAN TAIKHOAN { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HINHANH> HINHANH { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<KHUYENMAI> KHUYENMAI { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<YEUTHICH> YEUTHICH { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DIADIEM> DIADIEM1 { get; set; }
        public virtual DIADIEM DIADIEM2 { get; set; }
    }
}
