//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyAmThucNhaTrang.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class HINHANH
    {
        public int MaHA { get; set; }
        public string DuongDan { get; set; }
        public string LoaiHinhAnh { get; set; }
        public int ThuTu { get; set; }
        public int MaDD { get; set; }
    
        public virtual DIADIEM DIADIEM { get; set; }
    }
}
