//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyAmThucNhaTrang.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class KHUYENMAI
    {
        public int MaKM { get; set; }
        public string TenKM { get; set; }
        public System.DateTime NgayBatDau { get; set; }
        public System.DateTime NgayKetThuc { get; set; }
        public string NoiDungUuDai { get; set; }
        public string TrangThai { get; set; }
        public int MaDD { get; set; }
    
        public virtual DIADIEM DIADIEM { get; set; }
    }
}
