//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyAmThucNhaTrang.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class PHANHOI
    {
        public int MaPH { get; set; }
        public string NoiDung { get; set; }
        public System.DateTime NgayPhanHoi { get; set; }
        public int MaDG { get; set; }
        public int MaTK { get; set; }
    
        public virtual DANHGIA DANHGIA { get; set; }
        public virtual TAIKHOAN TAIKHOAN { get; set; }
    }
}
