//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyAmThucNhaTrang.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class YEUTHICH
    {
        public int MaYT { get; set; }
        public System.DateTime NgayLuu { get; set; }
        public int MaTK { get; set; }
        public int MaDD { get; set; }
    
        public virtual DIADIEM DIADIEM { get; set; }
        public virtual TAIKHOAN TAIKHOAN { get; set; }
    }
}
